# Generated by Django 5.2.15 on 2026-07-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('complaint_category', models.CharField(choices=[('Water Supply', 'Water Supply'), ('Drainage', 'Drainage'), ('Street Light', 'Street Light'), ('Road', 'Road'), ('Garbage', 'Garbage'), ('Security', 'Security'), ('Common Area', 'Common Area'), ('Others', 'Others')], max_length=30)),
                ('complaint_description', models.TextField()),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaints/')),
            ],
        ),
    ]
