# Generated by Django 5.2.15 on 2026-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('house_no', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('suggestion', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='suggestions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
