# Generated by Django 5.2.15 on 2026-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
