# Generated by Django 5.2.15 on 2026-07-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_complaint_complaint_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
