# Generated by Django 5.2.15 on 2026-07-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_suggestion_suggestion_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '🚀 Admin Portal',
                'verbose_name_plural': '🚀 Admin Portal',
            },
        ),
    ]
