# Generated by Django 5.2.15 on 2026-07-15 09:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery_image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='member_photo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
