# Generated by Django 5.2.15 on 2026-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(upload_to='gallery/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
